program-1-no-chrones: program-1.cpp
	g++ -std=gnu++11 program-1.cpp -I`chrones instrument c++ header-location` -DCHRONES_DISABLED -o program-1-no-chrones

program-1-yes-chrones: program-1.cpp
	g++ -std=gnu++11 program-1.cpp -I`chrones instrument c++ header-location` -o program-1-yes-chrones
